### PR TITLE
Initial Documentation for Patter

### PR DESCRIPTION
**Pull request by duerig**

### CODE REVIEW

**Comment by berg** [comment]
Hmm -- I don't think you wanted to include that merge commit in this pull request.

**Comment by duerig** [comment]
Not quite sure I understand. Ought I have rebased, fixed the conflict, then
just checked in as a FF commit?

**Comment by berg** [comment]
Yeah, probably. Your commit shouldn't touch all of those other files (like the README, etc.) It looks like you pulled off of orian's (old?) fork of the repo, rather than the master branch over here.

**Comment by berg** [comment]
To answer more directly, yes -- please rebase off of appdotnet/object-metadata's master branch, so that there's only a single commit containing just your changes.

**Comment by orianmarx** [comment]
Yeah I'm going to take down my fork so we don't run in to this confusion.

**Pull request closed without merging**
